import dash
from dash import html, dcc
import dash_bootstrap_components as dbc

dash.register_page(__name__, path='/', order=0)

# resume sample template from https://zety.com/
layout = html.Div([
    dcc.Markdown('# Hao Chen', style={'textAlign':'center'}),
    dcc.Markdown('Nanjing, China', style={'textAlign': 'center'}),

    dcc.Markdown('### Education', style={'textAlign': 'center'}),
    html.Hr(),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('09/2019 - current', style={'textAlign': 'center'})
        ], width=2),
        dbc.Col([
            dcc.Markdown('Nanjing Agricultural University (NAU), School of Finance\n'
                         'Bachelor of Management in Accounting',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li('GPA: 3.63/4.0 (90.52/100); Ranking: Top 20%'),
                html.Li('Honor: Second Prize Scholarship (2019)'),
                html.Li('Core Courses: Big Financial Data Analysis(A), Python Programming(A), Management Information System(A), Applied Statistics(A), Econometrics(A), Linear Algebra(A), Calculus, Probability Theory and Mathematical Statistics, Advanced Financial Accounting(A), Auditing(A), etc.'),
            ])
        ], width=7)
    ], justify='center'),

    dcc.Markdown('### Research Experience ', style={'textAlign': 'center'}),
    html.Hr(),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('03/2021 - 06/2022', style={'textAlign': 'center'})
        ], width=2),
        dbc.Col([
            dcc.Markdown('The effect of blockchain on stock price crash: a quantitative research\n'
                         'Undergraduate Research Training Program',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li('Built a dataset on 38 listed companies across 7 industries that integrated blockchain technology into operations and their stock price performance from 2017 to 2022;'),
                html.Li('Performed multiple linear regression analysis with backward elimination in STATA and used PSM(Propensity Score Matching) to do robustness check;'),
                html.Li('Results showed that the use of blockchain tech increased the risks of stock price crash.')
                          ])
        ], width=7)
    ], justify='center'),
    dcc.Markdown('### Working Experience ', style={'textAlign': 'center'}),
    html.Hr(),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('05/2022 - 08/2022', style={'textAlign': 'center'})
        ], width=2),

        dbc.Col([
            dcc.Markdown('Bigo Technology Pte. Ltd. (a network-based video broadcasting company)\n'
                         'Financial BP Intern',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li('Tracked, monitored and analyzed user data generated by Likee (a global short video platform) to improve user experience, retention, and conversion; '),
                html.Li(
                    'Wrote a competitive analysis report by analyzing the business model of 5 global short video platforms in terms of value proposition, revenue source, key operations, and cost structure based on first-hand data crawled from these platforms.'),

            ])
        ], width=7)
    ], justify='center'),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('07/2021 - 08/2021', style={'textAlign': 'center'})
        ], width=2),

        dbc.Col([
            dcc.Markdown('China Life Insurance Co. Ltd. \n'
                         'Summer Intern',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Created internal tools using Excel VBA and Macro to automate tax calculation and regular reporting;'),
                html.Li(
                    'Maintained and managed the insurance claims database using a Python crawler;'),
                html.Li(
                    'Used CRM and agency management systems to generate more leads and improve customer journey.'),

            ])
        ], width=7)
    ], justify='center'),
    dcc.Markdown('### Projects ', style={'textAlign': 'center'}),
    html.Hr(),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('05/2022 - 08/2022', style={'textAlign': 'center'})
        ], width=2),
        dbc.Col([
            dcc.Markdown('Independent Project: Financial Information Visualization Dashboard',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Used Python (plotly, sklearn, Numpy, Pandas) to create a website analytics dashboard REDHAWC for selected listed companies.'),
  ])
        ], width=7)
    ], justify='center'),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('03/2021 - 06/2022', style={'textAlign': 'center'})
        ], width=2),
        dbc.Col([
            dcc.Markdown('Kaggle Competition: NBME - Score Clinical Patient Notes',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Used DeBERTa model in Python to identify specific clinical concepts in patient notes;'),
                html.Li(
                    'Entered the Top 23%'),
            ])
        ], width=7)
    ], justify='center'),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('03/2022 - 05/2022', style={'textAlign': 'center'})
        ], width=2),
        dbc.Col([
            dcc.Markdown('Kaggle competition: H&M Personalized Fashion Recommendations',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Developed content-based recommendation systems in Python;'),
                html.Li(
                    'Entered the Top 27%'),
            ])
        ], width=7)
    ], justify='center'),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('10/2020 - 12/2020', style={'textAlign': 'center'})
        ], width=2),
        dbc.Col([
            dcc.Markdown('The 3rd Business Model Case Analysis Competition of NAU',
                         style={'white-space': 'pre','font-weight': 'bold'},
                         className='ms-3'),
            html.Ul([
                html.Li(
                    'Worked in a 3-person team to conduct a quantitative case study on Huawei Technologies Co., Ltd. based on data collected from annual reports, news reports, and third-party industrial research papers;'),
                html.Li(
                    'Visualized results in PowerBI and won the 1st prize.'),

            ])
        ], width=7)
    ], justify='center'),
    dcc.Markdown('### Skills', style={'textAlign': 'center'}),
    html.Hr(),
    dbc.Row([
        dbc.Col([
            dcc.Markdown('''
        * Language Skills: Chinese (native), English (fluent, 2nd prize in national English competitions in 2020&21) 
        * Computer Skills: Python, VBA, SQL, STATA,  Tableau, Power BI
        * Interests: Football
        ''')
        ], width={"size": 7, "offset": 1}),
    ], justify='center'),
])
